# Services environment variables

Create a file `services.env` containing something like

[source, shell]
----
DOMAIN=my.domain.org
MARIADB_TZ=Europe/Zurich
MARIADB_ROOT_PASSWORD=12345spaceballs
LB_DB_USER_PWD=12345spaceballs
LB_INSTALL_PWD=12345spaceballs
BAM_WEB_STATIC_USR=spaceman
BAM_WEB_STATIC_PWD=12345spaceballs
FORMS_APP_KEY=base64:MJhcpRe554PqcK7xvrxgmrkOW+/W+U8MeMG7WKjcPlA=
FORMS_DB_PASSWORD=12345spaceballs
FORMS_FRONT_API_SECRET=12345spaceballs
FORMS_JWT_SECRET:: encoded key
FORMS_MAIL_MAILER=log
FORMS_MAIL_ENCRYPTION=null
FORMS_MAIL_FROM_ADDRESS=forms@nowhere.place
FORMS_MAIL_HOST=smtp.nowhere
FORMS_MAIL_PASSWORD=12345spaceballs
FORMS_MAIL_PORT=25
FORMS_MAIL_USERNAME=nobody
FORMS_NUXT_API_SECRET=12345spaceballs
FORMS_PUSHER_APP_KEY=12345spaceballs
----

LB_DB_USER_PWD:: the username to be used by librebooking
LB_INSTALL_PWD:: the admin installation password for initial librebooking setup
BAM_WEB_STATIC_USR:: SSH user for updating static web content for 'bam' subdomain via SFTP
BAM_WEB_STATIC_PWD:: SHH user password for 'bam' SFTP
FORMS_APP_KEY:: base64 encoded key, prefix output of 'openssl rand -base64 32' with base64:
FORMS_DB_PASSWORD=12345spaceballs
FORMS_FRONT_API_SECRET:: key, use openssl rand or pwdgen
FORMS_JWT_SECRET:: long key, for example using 'openssl rand -hex 64'
FORMS_MAIL_MAILER:: either of log, smtp or null
FORMS_MAIL_ENCRYPTION:: null
FORMS_MAIL_FROM_ADDRESS:: valid email
FORMS_MAIL_HOST:: SMTP host
FORMS_MAIL_PASSWORD:: SMTP password
FORMS_MAIL_PORT:: SMTP port
FORMS_MAIL_USERNAME:: SMTP username
FORMS_NUXT_API_SECRET:: key, use openssl rand or pwdgen
FORMS_PUSHER_APP_KEY:: key
