services:
  doorcontroller:
    depends_on:
      mqtt-broker:
        condition: service_started
      mariadb:
        condition: service_started
      create_self_signed:
        condition: service_completed_successfully
    environment:
      - SITE="${SITE:?err}"
      - LB_DB_USER_PWD=${LB_DB_USER_PWD:?err}
    command: >
      --mqtt-broker ssl://mqtt-broker:8883
      --ca-file /etc/self_signed/ca/pub/ca.crt
      --client-cert /etc/self_signed/doorcontroller/pub/doorcontroller.crt
      --client-key /etc/self_signed/doorcontroller/priv/doorcontroller.key
      --site ${SITE:-}
      --db-host mariadb
      --db-name librebooking
      --db-user lb_user
      --db-pass ${LB_DB_USER_PWD}
    volumes:
      - cert_ca_pub:/etc/self_signed/ca/pub
      - cert_doorcontroller_priv:/etc/self_signed/doorcontroller/priv
      - cert_doorcontroller_pub:/etc/self_signed/doorcontroller/pub
