services:
  create_self_signed:
    image: alpine/openssl
    environment:
      - DIR=/etc/self_signed
      - COUNTRY=${COUNTRY:?err}
      - ORG=${ORG:?err}
      - DOMAIN=${DOMAIN:?err}
    entrypoint: create-keys.sh ${SELF_SIGN_KEYS:-}
    volumes:
      - ./openssl/ssl-functions.sh:/usr/local/bin/ssl-functions.sh
      - ./openssl/create-keys.sh:/usr/local/bin/create-keys.sh
      - cert_ca_priv:/etc/self_signed/ca/priv
      - cert_ca_pub:/etc/self_signed/ca/pub
      - cert_srv_priv:/etc/self_signed/srv/priv
      - cert_srv_pub:/etc/self_signed/srv/pub

volumes:
  cert_ca_priv:
  cert_ca_pub:
  cert_srv_priv:
  cert_srv_pub:
